name: 'userprofile API'

on:
  push:
    #paths: [ 'apis/userprofile/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'apis/userprofile/**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8.x
      uses: actions/setup-node@v1
      with:
        node-version: 8.x
    - run: npm ci
      working-directory: apis/userprofile
    - run: npm run build --if-present
      working-directory: apis/userprofile
    - run: npm test
      working-directory: apis/userprofile
    - uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ failure() }}
    - name: Build and publish Docker Image for API
      if: ${{ success() && github.ref == 'refs/heads/master' }}
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: 'publishdockerimage'
        token: ${{ secrets.PERSONAL_TOKEN }}
        inputs: '{ "image_name": "my-driving-userprofile", "docker_context": "apis/userprofile", "webapp_name": "openhackrvp3hz11userprofile" }'

  code_coverage:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: debug code coverage test
      run: echo 'executed code coverage'

  sonarcloud_scan:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: 'apis/userprofile/'
        args: >
          -Dsonar.organization=avanadeatopenhack202106
          -Dsonar.projectKey=avanadeatopenhack202106_openhack-team06
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
  deploy:
    needs: [code_coverage,sonarcloud_scan]
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: echo 'execute deploy'
